### ISSUE TITLE
how to copy all directlink Download . 

### ISSUE THREAD

**Issue by bobwatcherx** [jinix6/Terabox-dir#1]
i want copy all directlink download with 1 button  how to make it

my tele : https://t.me/bobwatcherx
thx

**Comment by jinix6** [comment]
Mean ?

**Comment by bobwatcherx** [comment]
video canot play sir

**Comment by jinix6** [comment]
Didn't play on the desktop

**Comment by bobwatcherx** [comment]
![Screenshot 2024-05-14 090111](https://github.com/jinix6/Terabox-dir/assets/52072811/75c1795a-6375-40ea-84e6-c0d8931c8dc4)
on web desktop canot play and download not work
https://teraboxapp.com/s/1z5YzxaJfS4hUy8yCjlU49Q

**Comment by jinix6** [comment]
Try it on mobile

**Comment by jinix6** [comment]
It's now testing
